# Generated by Django 4.2.11 on 2025-12-19 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=64)),
                ('parameters', models.JSONField()),
                ('result_count', models.IntegerField(blank=True, null=True)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('sha256', models.CharField(max_length=64)),
                ('prev_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['action', 'occurred_at'], name='audit_audit_action_b398e4_idx')],
            },
        ),
    ]
