# Generated by Django 4.2.11 on 2025-12-19 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=512)),
                ('sent_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('sha256', models.CharField(max_length=64)),
                ('s3_object_key', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField()),
                ('has_html', models.BooleanField(default=False)),
                ('has_text', models.BooleanField(default=True)),
                ('immutable_flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.mailbox')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archivedemail')),
            ],
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('status', models.CharField(default='QUEUED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_s3_key', models.CharField(blank=True, max_length=512, null=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.mailbox')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('s3_object_key', models.CharField(max_length=512)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='archive.archivedemail')),
            ],
        ),
        migrations.CreateModel(
            name='EmailParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FROM', 'FROM'), ('TO', 'TO'), ('CC', 'CC'), ('BCC', 'BCC')], max_length=4)),
                ('address', models.EmailField(max_length=254)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='archive.archivedemail')),
            ],
            options={
                'unique_together': {('email', 'type', 'address')},
            },
        ),
        migrations.AddIndex(
            model_name='archivedemail',
            index=models.Index(fields=['mailbox', 'received_at'], name='archive_arc_mailbox_ebe1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedemail',
            index=models.Index(fields=['department', 'received_at'], name='archive_arc_departm_15a997_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='archivedemail',
            unique_together={('message_id', 'mailbox')},
        ),
    ]
