# Generated by Django 4.2.11 on 2025-12-19 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailboxaccess',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='accounts.mailbox'),
        ),
        migrations.AlterField(
            model_name='mailboxaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
